### ISSUE TITLE
filtering data (product names with spaces)

### ISSUE THREAD

**Issue by sdegenaar** [nitrite/nitrite-flutter#16]
Hi, I have product names I need to search for. 

The product names can contain spaces, (multiple words). Search requirement include starts with and contains.

I got it working with fulltext index and using 

await collection.find(filter: where(PRODUCT_NAME_FIELD).text('$searchTerm*')); and 
await collection.find(filter: where(PRODUCT_NAME_FIELD).text('*$searchTerm*'));

Is this the best and most efficient way to do it or can I achieve similar using a nonUnique index and some other search patterns.

Thanks in advance

**Comment by anidotnet** [comment]
It is the most efficient way. You have to use fulltext index and `text` filter in your use case. I hope for contains, you wanted to mean '\*$searchTerm\*', the markdown format made it in italics instead.

**Comment by sdegenaar** [comment]
Thanks for prompt reply. Yes i did mean that for contains, must have formatted out. Great package. Working perfectly for me so far. Thanks again
